[package]
name = "matrix_processor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "matrix_operations"
path = "src/lib.rs"

[dependencies]
#gtk = "0.14.3"
#gdk = "0.14.3"
#pango = "0.14.8"
